build:
	go build main.go
test1:
	nohup ./main -clientId=client1 > test1.log 2>&1  &

test2:
	nohup ./main -clientId=client2 > test2.log 2>&1  &

test3:
	nohup ./main -clientId=client3 > test3.log 2>&1  &
